version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'

  front:
    build:
      context: './client-next'
      dockerfile: 'Dockerfile'
      args:
        - REACT_APP_API_URL=http://localhost:4000
    ports:
      - '3000:3000'
    volumes:
      - ./client-next:/app:delegated
      - /app/node_modules
    command: 'yarn dev'

  back:
    depends_on:
      - postgres
    build: './server'
    ports:
      - '4000:4000'
    command: 'yarn start'
    volumes:
      - ./server:/app:delegated
      - /app/node_modules
