version: '3'
services:
  postgres:
    image: 'postgres:latest'
    env_file: .env
    volumes:
      - db_dev:/var/lib/postgresql/data

  front:
    build:
      context: './client-next'
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=http://localhost:4000
    ports:
      - '3000:3000'
    command: 'yarn start'

  back:
    depends_on:
      - postgres
    build:
      context: './server'
      args:
        - POSTGRES_USER
        - POSTGRES_DB
        - POSTGRES_PASSWORD
    env_file: .env
    ports:
      - '4000:4000'
    command: 'yarn start'

volumes:
  ? db_dev
